version: '3.8'

services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - 4566:4566
    command: ["./wait-for-s3.sh"]
#    volumes:
#      - ./bootstrap-s3.sh:/docker-entrypoint-initaws.d/bootstrap-s3.sh